apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-6wxy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-6wxy
    app.kubernetes.io/part-of: dotnet-component
  name: devfile-sample-dotnet60-basic-6wxy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-6wxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-6wxy
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-thzj-tenant/dotnet-component/devfile-sample-dotnet60-basic-6wxy@sha256:0212cda16bd460afbb97ddf3d067b586808ee4f4b90066f0d19a2186a9537641
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
