apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dotnet60-basic-6wxy
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-thzj-tenant/dotnet-component/devfile-sample-dotnet60-basic-6wxy@sha256:0212cda16bd460afbb97ddf3d067b586808ee4f4b90066f0d19a2186a9537641
        name: main
        resources: {}
status: {}
